### ISSUE TITLE
Error showing when using the plugin on a dev site running 5.5.1

### ISSUE THREAD

**Issue by lukecav** [norcross/temporary-admin-user#13]
`Fatal error: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /chroot/home/a80f149d/no-install.com/html/wp-content/plugins/temporary-admin-user-master/includes/class-helper.php:60 Stack trace: #0 /chroot/home/a80f149d/no-install.com/html/wp-content/plugins/temporary-admin-user-master/includes/class-helper.php(60): DateTimeZone->__construct('') #1 /chroot/home/a80f149d/no-install.com/html/wp-content/plugins/temporary-admin-user-master/includes/class-user-table.php(257): TempAdminUser_Helper::gmt_to_local(1601404389, 'Y/m/d g:i:s a') #2 /chroot/home/a80f149d/no-install.com/html/wp-admin/includes/class-wp-list-table.php(1405): TemporaryAdminUsers_Table->column_created(Array) #3 /chroot/home/a80f149d/no-install.com/html/wp-admin/includes/class-wp-list-table.php(1350): WP_List_Table->single_row_columns(Array) #4 /chroot/home/a80f149d/no-install.com/html/wp-admin/includes/class-wp-list-table.php(1337): WP_List_Table->single_row(Array) #5 /chroot/home/a80f149d/no-install.com/html/wp-admin/includes/c in /chroot/home/a80f149d/no-install.com/html/wp-content/plugins/temporary-admin-user-master/includes/class-helper.php on line 60`

![Existing temp users](https://user-images.githubusercontent.com/5797332/94604794-6848a880-0255-11eb-8083-b89e0bf9bc8c.png)

**Comment by norcross** [comment]
what is the time zone set in the general settings?

**Comment by norcross** [comment]
this happened due to the settings being a modified UTC and not a standard timezone name. i've added a secondary check to make sure it doesn't fail.
